# Generated by Django 5.2 on 2025-04-05 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_pairs', to='market_data.currency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_pairs', to='market_data.currency')),
            ],
        ),
        migrations.CreateModel(
            name='EconomicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('forecast_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='market_data.economicindicator')),
            ],
            options={
                'indexes': [models.Index(fields=['indicator', 'timestamp'], name='market_data_indicat_d86af3_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_dfa776_idx')],
                'unique_together': {('indicator', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=24)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market_data.currencypair')),
            ],
            options={
                'indexes': [models.Index(fields=['pair', 'timestamp'], name='market_data_pair_id_5bf055_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_b1b9de_idx')],
                'unique_together': {('pair', 'timestamp')},
            },
        ),
    ]
